package com.amaris.sensorprocessor.service;

import com.amaris.sensorprocessor.entity.DatabaseConnectionConfig;
import org.springframework.core.env.Environment;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Properties;

@Service
public class DatabaseConnectionConfigService {

    private static final String MYSQL = "mysql";
    private static final String SQLITE = "sqlite";
    private static final Path CONFIG_PATH = Path.of("config", "database-config.properties");

    private final Environment environment;

    public DatabaseConnectionConfigService(Environment environment) {
        this.environment = environment;
    }

    public Map<String, Object> getCurrentConfig() {
        String url = environment.getProperty("spring.datasource.url", "");
        DatabaseConnectionConfig config = fromJdbcUrl(url);
        config.setUsername(environment.getProperty("spring.datasource.username", ""));

        Map<String, Object> response = toResponse(config);
        response.put("configuredFile", CONFIG_PATH.toAbsolutePath().toString());
        response.put("fileExists", Files.exists(CONFIG_PATH));
        response.put("activeDatabase", describeJdbcUrl(url));

        Properties savedProperties = readSavedProperties();
        String savedUrl = savedProperties.getProperty("spring.datasource.url", "");
        response.put("savedDatabase", describeJdbcUrl(savedUrl));
        response.put("savedMatchesActive", sameDatabaseUrl(url, savedUrl));
        return response;
    }

    public Map<String, Object> testConnection(DatabaseConnectionConfig config) {
        ResolvedDatabaseConfig resolved = resolve(config, true);
        return testResolvedConnection(resolved);
    }

    private Map<String, Object> testResolvedConnection(ResolvedDatabaseConfig resolved) {
        try {
            Class.forName(resolved.driverClassName());
            try (Connection connection = DriverManager.getConnection(
                    resolved.url(),
                    resolved.username(),
                    resolved.password()
            )) {
                boolean valid = connection.isValid(5);
                return Map.of(
                        "success", valid,
                        "message", valid ? "Connection successful" : "Connection refused"
                );
            }
        } catch (ClassNotFoundException e) {
            return Map.of("success", false, "message", "Database driver not found: " + resolved.driverClassName());
        } catch (SQLException e) {
            return Map.of("success", false, "message", e.getMessage());
        }
    }

    public Map<String, Object> saveConfig(DatabaseConnectionConfig config) throws IOException {
        ResolvedDatabaseConfig resolved = resolve(config, true);
        Map<String, Object> testResult = testResolvedConnection(resolved);
        if (!Boolean.TRUE.equals(testResult.get("success"))) {
            return testResult;
        }

        Files.createDirectories(CONFIG_PATH.getParent());

        Properties properties = new Properties();
        properties.setProperty("spring.datasource.url", resolved.url());
        properties.setProperty("spring.datasource.driver-class-name", resolved.driverClassName());
        properties.setProperty("spring.datasource.username", resolved.username());
        properties.setProperty("spring.datasource.password", resolved.password());
        properties.setProperty("spring.jpa.database-platform", resolved.jpaDialect());

        try (OutputStream outputStream = Files.newOutputStream(CONFIG_PATH)) {
            properties.store(outputStream, "Local database configuration generated by IoT Management App");
        }

        return Map.of(
                "success", true,
                "message", "Database configuration saved. Restart the application to apply it.",
                "restartRequired", true,
                "path", CONFIG_PATH.toAbsolutePath().toString()
        );
    }

    private ResolvedDatabaseConfig resolve(DatabaseConnectionConfig config, boolean allowExistingPassword) {
        String type = normalizedType(config.getType());
        if (MYSQL.equals(type)) {
            String host = required(config.getHost(), "Host is required");
            int port = config.getPort() == null ? 3306 : config.getPort();
            String databaseName = required(config.getDatabaseName(), "Database name is required");
            String username = nullToEmpty(config.getUsername());
            String password = resolvePassword(config.getPassword(), allowExistingPassword);
            String url = "jdbc:mysql://" + host + ":" + port + "/" + databaseName
                    + "?sslMode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC";
            return new ResolvedDatabaseConfig(
                    url,
                    username,
                    password,
                    "com.mysql.cj.jdbc.Driver",
                    "org.hibernate.dialect.MySQLDialect"
            );
        }

        if (SQLITE.equals(type)) {
            String sqlitePath = required(config.getSqlitePath(), "SQLite database path is required");
            return new ResolvedDatabaseConfig(
                    "jdbc:sqlite:" + sqlitePath,
                    "",
                    "",
                    "org.sqlite.JDBC",
                    "org.hibernate.community.dialect.SQLiteDialect"
            );
        }

        throw new IllegalArgumentException("Unsupported database type");
    }

    private String resolvePassword(String password, boolean allowExistingPassword) {
        if (password != null && !password.isBlank()) {
            return password;
        }
        if (!allowExistingPassword) {
            return "";
        }
        return readSavedPassword();
    }

    private String readSavedPassword() {
        return readSavedProperties().getProperty("spring.datasource.password", "");
    }

    private Properties readSavedProperties() {
        Properties properties = new Properties();
        if (!Files.exists(CONFIG_PATH)) {
            return properties;
        }
        try (InputStream inputStream = Files.newInputStream(CONFIG_PATH)) {
            properties.load(inputStream);
        } catch (IOException e) {
            return properties;
        }
        return properties;
    }

    private DatabaseConnectionConfig fromJdbcUrl(String url) {
        DatabaseConnectionConfig config = new DatabaseConnectionConfig();
        if (url == null || url.isBlank()) {
            config.setType(MYSQL);
            config.setPort(3306);
            return config;
        }

        if (url.startsWith("jdbc:sqlite:")) {
            config.setType(SQLITE);
            config.setSqlitePath(url.substring("jdbc:sqlite:".length()));
            return config;
        }

        config.setType(MYSQL);
        config.setPort(3306);
        String withoutPrefix = url.replaceFirst("^jdbc:mysql://", "");
        String hostPortAndDb = withoutPrefix.split("\\?")[0];
        String[] hostAndRest = hostPortAndDb.split("/", 2);
        if (hostAndRest.length > 0) {
            String[] hostAndPort = hostAndRest[0].split(":", 2);
            config.setHost(hostAndPort[0]);
            if (hostAndPort.length > 1) {
                try {
                    config.setPort(Integer.parseInt(hostAndPort[1]));
                } catch (NumberFormatException ignored) {
                    config.setPort(3306);
                }
            }
        }
        if (hostAndRest.length > 1) {
            config.setDatabaseName(hostAndRest[1]);
        }
        return config;
    }

    private Map<String, Object> toResponse(DatabaseConnectionConfig config) {
        Map<String, Object> response = new LinkedHashMap<>();
        response.put("type", normalizedType(config.getType()));
        response.put("host", nullToEmpty(config.getHost()));
        response.put("port", config.getPort() == null ? 3306 : config.getPort());
        response.put("databaseName", nullToEmpty(config.getDatabaseName()));
        response.put("username", nullToEmpty(config.getUsername()));
        response.put("sqlitePath", nullToEmpty(config.getSqlitePath()));
        return response;
    }

    private boolean sameDatabaseUrl(String activeUrl, String savedUrl) {
        if (savedUrl == null || savedUrl.isBlank()) {
            return false;
        }
        return Objects.equals(normalizedJdbcUrl(activeUrl), normalizedJdbcUrl(savedUrl));
    }

    private String normalizedJdbcUrl(String url) {
        return url == null ? "" : url.replace("\\:", ":").replace("\\=", "=").trim();
    }

    private String describeJdbcUrl(String url) {
        DatabaseConnectionConfig config = fromJdbcUrl(normalizedJdbcUrl(url));
        if (SQLITE.equals(normalizedType(config.getType()))) {
            return "SQLite";
        }

        String host = nullToEmpty(config.getHost());
        String databaseName = nullToEmpty(config.getDatabaseName());
        if (host.isBlank() && databaseName.isBlank()) {
            return "";
        }
        return host + "/" + databaseName;
    }

    private String normalizedType(String type) {
        if (SQLITE.equalsIgnoreCase(type)) {
            return SQLITE;
        }
        return MYSQL;
    }

    private String required(String value, String message) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(message);
        }
        return value.trim();
    }

    private String nullToEmpty(String value) {
        return value == null ? "" : value;
    }

    private record ResolvedDatabaseConfig(
            String url,
            String username,
            String password,
            String driverClassName,
            String jpaDialect
    ) {
    }
}
