name: Deploy2 to Raspberry Pi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Give execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Build project
        run: ./mvnw clean package -DskipTests

      - name: Install OpenVPN
        run: |
          sudo apt-get update
          wget https://github.com/OpenVPN/openvpn3/releases/download/release-2.5.7/openvpn3-2.5.7-1_amd64.deb
          sudo dpkg -i openvpn3-2.5.7-1_amd64.deb
          mkdir -p ./tmp
          echo "${{ secrets.OVPN_CONFIG }}" | sudo tee ./tmp/config > /dev/null
          sudo chmod 777 ./tmp/config

      - name: Connect to VPN
        uses: kota65535/github-openvpn-connect-action@v2
        with:
          config_file: ./tmp/config
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          pkcs12_file: ${{ secrets.OVPN_CLIENT_P12 }}
          tls_auth_key: ${{ secrets.OVPN_TLS_AUTH_KEY }}

      - name: Copy files to Raspberry Pi
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.RASPBERRY_HOST }}
          username: ${{ secrets.RASPBERRY_USER }}
          key: ${{ secrets.RASPBERRY_SSH_KEY }}
          port: 22
          source: "target/sensorprocessor-0.0.1-SNAPSHOT.jar"
          target: "/opt/app/"

      - name: Restart Spring app
        run: ssh -i ${{ secrets.RASPBERRY_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.RASPBERRY_USER }}@${{ secrets.RASPBERRY_HOST }} "sudo systemctl restart sensorprocessor.service"
