name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: ./mvnw clean package -DskipTests

      - name: Copy files to Raspberry Pi
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.RASPBERRY_HOST }}
          username: ${{ secrets.RASPBERRY_USER }}
          key: ${{ secrets.RASPBERRY_SSH_KEY }}
          port: 22
          source: "target/*.jar"
          destination: "/opt/app/"

      - name: Restart Spring app
        run: ssh -i ${{ secrets.RASPBERRY_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.RASPBERRY_USER }}@${{ secrets.RASPBERRY_HOST }} "sudo systemctl restart sensorprocessor.service"
        # run: ssh -i 10.243.129.10 -o StrictHostKeyChecking=no user2@10.243.129.10 "sudo systemctl restart sensorprocessor.service"
