name: Deploy to Azure Cloud with Docker Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Give execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Build project
        run: ./mvnw clean package -DskipTests

      - name: Build and tag Docker image
        run: |
          docker build --platform linux/amd64 --no-cache -t localhost:5000/sensorprocessor:latest .

      - name: Stop and remove existing Docker container and image
        run: |
          sshpass -p "${{ secrets.AZURE_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} '
            echo "${{ secrets.AZURE_PASSWORD }}" | sudo -S docker stop sensorprocessor || true && \
            echo "${{ secrets.AZURE_PASSWORD }}" | sudo -S docker rm sensorprocessor || true && \
            echo "${{ secrets.AZURE_PASSWORD }}" | sudo -S docker rmi localhost:5000/sensorprocessor:latest || true
            '

      #      - name: Stop and remove existing Docker container and image
      #        run: |
      #          sshpass -p "Mantu@ntuDev2025!" ssh -o StrictHostKeyChecking=no azureuser@20.82.0.151 '
      #            echo "Mantu@ntuDev2025!" | sudo -S docker stop sensorprocessor || true && \
      #            echo "Mantu@ntuDev2025!" | sudo -S docker rm sensorprocessor || true && \
      #            echo "Mantu@ntuDev2025!" | sudo -S docker rmi localhost:5000/sensorprocessor:latest || true
      #            '

      - name: Copy Docker image to Azure Cloud
        run: |
          echo "Starting Docker save"
          docker save localhost:5000/sensorprocessor:latest -o image.tar
          echo "Docker save completed"
          echo "Compressing image"
          gzip image.tar
          echo "Compression completed"
          echo "Starting SCP transfer"
          sshpass -p "${{ secrets.AZURE_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} 'if [ -e /tmp/appPrincipal/image.tar.gz ]; then echo ${{ secrets.AZURE_PASSWORD }} | sudo -S rm -f /tmp/appPrincipal/image.tar.gz; fi'
          sshpass -p "${{ secrets.AZURE_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} 'if [ -e /tmp/appPrincipal/image.tar ]; then echo ${{ secrets.AZURE_PASSWORD }} | sudo -S rm -f /tmp/appPrincipal/image.tar; fi'
          sshpass -p "${{ secrets.AZURE_PASSWORD }}" scp -o StrictHostKeyChecking=no image.tar.gz ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }}:/tmp/appPrincipal
          echo "SCP transfer completed"
          echo "Starting SSH to Azure Cloud"
          sshpass -p "${{ secrets.AZURE_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} 'echo ${{ secrets.AZURE_PASSWORD }} | sudo -S bash -c "gunzip -f /tmp/appPrincipal/image.tar.gz && docker load -i /tmp/appPrincipal/image.tar"'
          echo "SSH and Docker load completed"

      #      - name: Copy Docker image to Azure Cloud
      #        run: |
      #          echo "Starting Docker save"
      #          docker save localhost:5000/sensorprocessor:latest -o image.tar
      #          echo "Docker save completed"
      #          echo "Compressing image"
      #          gzip image.tar
      #          echo "Compression completed"
      #          echo "Starting SCP transfer"
      #          sshpass -p "Mantu@ntuDev2025!" ssh -o StrictHostKeyChecking=no azureuser@20.82.0.151 'if [ -e /tmp/appPrincipal/image.tar.gz ]; then echo "Mantu@ntuDev2025!" | sudo -S rm -f /tmp/appPrincipal/image.tar.gz; fi'
      #          sshpass -p "Mantu@ntuDev2025!" ssh -o StrictHostKeyChecking=no azureuser@20.82.0.151 'if [ -e /tmp/appPrincipal/image.tar ]; then echo "Mantu@ntuDev2025!" | sudo -S rm -f /tmp/appPrincipal/image.tar; fi'
      #          sshpass -p "Mantu@ntuDev2025!" scp -o StrictHostKeyChecking=no image.tar.gz azureuser@20.82.0.151:/tmp/appPrincipal
      #          echo "SCP transfer completed"
      #          echo "Starting SSH to Azure Cloud"
      #          sshpass -p "Mantu@ntuDev2025!" ssh -o StrictHostKeyChecking=no azureuser@20.82.0.151 'echo "Mantu@ntuDev2025!" | sudo -S bash -c "gunzip -f /tmp/appPrincipal/image.tar.gz && docker load -i /tmp/appPrincipal/image.tar"'
      #          echo "SSH and Docker load completed"

      - name: Run Docker Compose on Azure Cloud
        run: |
          sshpass -p "${{ secrets.AZURE_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} 'echo "${{ secrets.AZURE_PASSWORD }}" | sudo -S docker-compose -f /opt/app/docker-compose.yml up -d'

#      - name: Run Docker Compose on Azure Cloud
#        run: |
#          sshpass -p "Mantu@ntuDev2025!" ssh -o StrictHostKeyChecking=no azureuser@20.82.0.151 'echo "Mantu@ntuDev2025!" | sudo -S docker compose -f /opt/app/docker-compose.yml up -d'
